apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aj9n4abg8-nodejs
  janus-idp.io/tekton: aj9n4abg8-nodejs
  backstage.io/kubernetes-id: aj9n4abg8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aj9n4abg8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
